# Generated by Django 3.1.1 on 2020-09-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
