# Generated by Django 3.1.1 on 2020-09-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0002_volunteer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('prefer not to say', 'prefer not to say')], max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=200, null=True)),
                ('recoverydate', models.DateField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
